server:
  port: 80

spring:
  # 数据源配置
  datasource:
    username: root
    password: lyz950725
    url: jdbc:mysql://localhost:3306/security?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false # 关闭thymeleaf缓存

luyuze:
  security:
    authentication:
      loginPage: /login/page # 响应认证页面的URL
      loginProcessingUrl: /login/form # 登陆表单提交处理的url
      usernameParameter: name # 登陆表单提交的用户名的属性名
      passwordParameter: pwd # 登陆表单提交的密码的属性名
      staticPaths: # 静态资源
        - /dist/**
        - /modules/**
        - /plugins/**
      loginType: REDIRECT # 认证之后响应的类型： JSON/REDIRECT
      imageCodeUrl: /code/image # 获取图形验证码地址
      mobileCodeUrl: /code/mobile # 发送手机验证码地址
      mobilePage: /mobile/page # 前往手机登陆页面
      tokenValiditySeconds: 604800